package com.kaipai.service.actor.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.kaipai.mapper.actor.*; import com.kaipai.mapper.card.ShareCardAssetMapper; import com.kaipai.model.actor.dto.*; import com.kaipai.model.actor.entity.*; import com.kaipai.model.card.entity.ShareCardAsset; import com.kaipai.service.actor.*;
import java.time.Duration; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor
public class ActorMediaAssetServiceImpl implements ActorMediaAssetService {
    private final ActorMediaAssetMapper assetMapper; private final ActorProfileMapper profileMapper; private final ActorProfileAssetMapper profileAssetMapper; private final ActorWorkAssetMapper workAssetMapper; private final ShareCardAssetMapper shareAssetMapper; private final PrivateActorMediaStorage storage;
    public ActorAssetRespDTO createReadyAsset(Long userId,String mediaType,String category,PrivateActorMediaStorage.StoredObjectRef object,String name,String mime,Long size){ ActorMediaAsset a=new ActorMediaAsset(); a.setUserId(userId);a.setMediaType(mediaType);a.setCategoryCode(category);a.setStorageProvider(object.storageProvider());a.setBucketCode(object.bucketCode());a.setObjectKey(object.objectKey());a.setThumbnailObjectKey(object.thumbnailObjectKey());a.setOriginalName(name);a.setMimeType(mime);a.setSizeBytes(size);a.setProcessStatus("ready");a.setSourceType("upload");assetMapper.insert(a);return dto(a); }
    public void requireOwnedReadyPhoto(Long userId,Long assetId){ ActorMediaAsset a=require(userId,assetId); if(!"photo".equals(a.getMediaType())||!"ready".equals(a.getProcessStatus())) throw ProfileDomainErrorCode.PROFILE_ASSET_NOT_READY.toException(); }
    public ActorAssetAccessUrlRespDTO issueOwnerAccessUrl(Long userId,Long assetId){ ActorMediaAsset a=require(userId,assetId); if(!"ready".equals(a.getProcessStatus())) throw ProfileDomainErrorCode.PROFILE_ASSET_NOT_READY.toException(); var signed=storage.issueAccessUrl(a.getBucketCode(),a.getObjectKey(),Duration.ofMinutes(10)); return new ActorAssetAccessUrlRespDTO(signed.accessUrl(),signed.expiresAt()); }
    @Transactional(rollbackFor=Exception.class) public void delete(Long userId,Long assetId){ ActorMediaAsset a=require(userId,assetId); if(profileMapper.selectCount(new LambdaQueryWrapper<ActorProfile>().eq(ActorProfile::getAvatarAssetId,assetId).or().eq(ActorProfile::getCurrentResumeAssetId,assetId))>0||profileAssetMapper.selectCount(new LambdaQueryWrapper<ActorProfileAsset>().eq(ActorProfileAsset::getAssetId,assetId))>0||workAssetMapper.selectCount(new LambdaQueryWrapper<ActorWorkAsset>().eq(ActorWorkAsset::getAssetId,assetId))>0||shareAssetMapper.selectCount(new LambdaQueryWrapper<ShareCardAsset>().eq(ShareCardAsset::getAssetId,assetId))>0) throw ProfileDomainErrorCode.PROFILE_ASSET_IN_USE.toException(); assetMapper.deleteById(assetId); storage.delete(a.getBucketCode(),a.getObjectKey()); }
    private ActorMediaAsset require(Long userId,Long id){ ActorMediaAsset a=assetMapper.selectOne(new LambdaQueryWrapper<ActorMediaAsset>().eq(ActorMediaAsset::getAssetId,id).eq(ActorMediaAsset::getUserId,userId).last("limit 1")); if(a==null) throw ProfileDomainErrorCode.PROFILE_ASSET_NOT_FOUND.toException(); return a; }
    private ActorAssetRespDTO dto(ActorMediaAsset a){ ActorAssetRespDTO d=new ActorAssetRespDTO();d.setAssetId(a.getAssetId());d.setMediaType(a.getMediaType());d.setCategoryCode(a.getCategoryCode());d.setOriginalName(a.getOriginalName());d.setMimeType(a.getMimeType());d.setSizeBytes(a.getSizeBytes());d.setProcessStatus(a.getProcessStatus());return d; }
}
