package com.kaipai.service.ai.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.fasterxml.jackson.databind.ObjectMapper; import com.kaipai.common.exception.BizException; import com.kaipai.mapper.ai.*; import com.kaipai.model.ai.dto.*; import com.kaipai.model.ai.entity.*; import com.kaipai.service.ai.*; import java.net.URI; import java.time.LocalDateTime; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.util.StringUtils;
@Service @RequiredArgsConstructor public class ProfileImportConfigServiceImpl implements ProfileImportConfigService { private final AiProfileImportConfigMapper mapper; private final AiProfileImportConfigAuditMapper auditMapper; private final AiProviderSecretCryptoService crypto; private final ProfileImportConnectionTester tester; private final ObjectMapper json;
 private AiProfileImportConfig config(){AiProfileImportConfig c=mapper.selectOne(new LambdaQueryWrapper<AiProfileImportConfig>().eq(AiProfileImportConfig::getProviderCode,"deepseek").last("limit 1"));if(c==null){c=new AiProfileImportConfig();c.setProviderCode("deepseek");c.setDisplayName("DeepSeek 资料导入");c.setEnabled(false);}return c;}
 public ProfileImportConfigRespDTO savePublicConfig(Long op,ProfileImportPublicConfigUpdateDTO d){validateEndpoint(d.getEndpoint());AiProfileImportConfig c=config();c.setEndpoint(d.getEndpoint());c.setModelName(d.getModelName());c.setConnectTimeoutMs(d.getConnectTimeoutMs());c.setReadTimeoutMs(d.getReadTimeoutMs());c.setMaxInputChars(d.getMaxInputChars());c.setMaxOutputTokens(d.getMaxOutputTokens());c.setPerUserDailyLimit(d.getPerUserDailyLimit());reset(c);persist(c);audit(op,c,"public_config_update","success");return dto(c);}
 public ProfileImportConfigRespDTO saveSecret(Long op,ProfileImportSecretUpdateDTO d){if(d==null||!StringUtils.hasText(d.apiKey()))throw new BizException("DeepSeek API Key 不能为空");AiProfileImportConfig c=config();try{c.setSecretConfigCiphertext(crypto.encrypt(json.writeValueAsString(java.util.Map.of("apiKey",d.apiKey()))));}catch(Exception e){throw new BizException("密钥保存失败");}c.setSecretMaskJson(mask(d.apiKey()));reset(c);persist(c);audit(op,c,"secret_update","success");return dto(c);}
 public ProfileImportConfigRespDTO testConnection(Long op){AiProfileImportConfig c=config();if(!StringUtils.hasText(c.getSecretConfigCiphertext()))throw new BizException("请先配置密钥");try{String plain=crypto.decrypt(c.getSecretConfigCiphertext());String key=json.readTree(plain).path("apiKey").asText();tester.test(c,key);c.setLastTestStatus("success");c.setLastTestAt(LocalDateTime.now());c.setLastTestMessage("连接成功");}catch(Exception e){c.setLastTestStatus("failed");c.setLastTestMessage("连接失败");}persist(c);return dto(c);}
 public ProfileImportConfigRespDTO setEnabled(Long op,boolean enabled){AiProfileImportConfig c=config();if(enabled&&!ready(c))throw new BizException("配置未通过连接测试");c.setEnabled(enabled);persist(c);return dto(c);}
 public ProfileImportCapabilityRespDTO capability(){AiProfileImportConfig c=config();boolean ok=Boolean.TRUE.equals(c.getEnabled())&&ready(c);return new ProfileImportCapabilityRespDTO(ok,ok?null:"智能导入未启用");}
 private boolean ready(AiProfileImportConfig c){return StringUtils.hasText(c.getEndpoint())&&StringUtils.hasText(c.getModelName())&&StringUtils.hasText(c.getSecretConfigCiphertext())&&"success".equals(c.getLastTestStatus());}
 private void reset(AiProfileImportConfig c){c.setEnabled(false);c.setLastTestStatus(null);c.setLastTestAt(null);c.setLastTestMessage(null);}
 private void persist(AiProfileImportConfig c){if(c.getConfigId()==null)mapper.insert(c);else mapper.updateById(c);}
 private void audit(Long op,AiProfileImportConfig c,String action,String status){AiProfileImportConfigAudit a=new AiProfileImportConfigAudit();a.setConfigId(c.getConfigId());a.setActionCode(action);a.setAfterSecretMaskJson(c.getSecretMaskJson());a.setOperatorId(op);a.setResultStatus(status);auditMapper.insert(a);}
 private void validateEndpoint(String endpoint){try{URI uri=URI.create(endpoint);if(!"https".equalsIgnoreCase(uri.getScheme())||!"api.deepseek.com".equalsIgnoreCase(uri.getHost()))throw new Exception();}catch(Exception e){throw new BizException("仅允许 DeepSeek HTTPS 官方接口");}}
 private String mask(String key){String tail=key.substring(Math.max(0,key.length()-4));return "****"+tail;} private ProfileImportConfigRespDTO dto(AiProfileImportConfig c){ProfileImportConfigRespDTO d=new ProfileImportConfigRespDTO();d.setEnabled(Boolean.TRUE.equals(c.getEnabled()));d.setAvailable(Boolean.TRUE.equals(c.getEnabled())&&ready(c));d.setEndpoint(c.getEndpoint());d.setModelName(c.getModelName());d.setSecretMask(c.getSecretMaskJson());d.setLastTestStatus(c.getLastTestStatus());return d;} }
