CREATE TABLE `ai_resume_notification_delivery` (
  `delivery_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `failure_id` VARCHAR(64) NOT NULL COMMENT 'ai failure id',
  `failure_request_id` VARCHAR(128) DEFAULT NULL COMMENT 'ai failure request id',
  `user_id` BIGINT DEFAULT NULL COMMENT 'actor user id',
  `assigned_admin_user_id` BIGINT DEFAULT NULL COMMENT 'assigned admin user id',
  `recipient_type` VARCHAR(32) NOT NULL DEFAULT 'admin_user' COMMENT 'admin_user, external',
  `recipient_admin_user_id` BIGINT DEFAULT NULL COMMENT 'recipient admin user id',
  `recipient_name` VARCHAR(64) DEFAULT NULL COMMENT 'recipient display name',
  `recipient_phone` VARCHAR(32) DEFAULT NULL COMMENT 'recipient phone',
  `recipient_email` VARCHAR(128) DEFAULT NULL COMMENT 'recipient email',
  `channel_code` VARCHAR(32) NOT NULL DEFAULT 'manual' COMMENT 'manual, sms, email, webhook',
  `provider_code` VARCHAR(64) DEFAULT NULL COMMENT 'provider code',
  `provider_message_id` VARCHAR(128) DEFAULT NULL COMMENT 'provider message id',
  `send_source_type` VARCHAR(32) DEFAULT NULL COMMENT 'manual_admin_record, governance_sweep, provider_retry',
  `send_status` VARCHAR(32) DEFAULT NULL COMMENT 'pending_send, sent, send_failed',
  `send_requested_at` DATETIME DEFAULT NULL COMMENT 'send requested time',
  `sent_at` DATETIME DEFAULT NULL COMMENT 'sent time',
  `send_failure_reason` VARCHAR(255) DEFAULT NULL COMMENT 'send failure reason',
  `send_operator_admin_user_id` BIGINT DEFAULT NULL COMMENT 'operator admin user id for send',
  `send_operator_admin_user_name` VARCHAR(64) DEFAULT NULL COMMENT 'operator admin user name for send',
  `receipt_source_type` VARCHAR(32) DEFAULT NULL COMMENT 'manual_admin_receipt, provider_callback',
  `receipt_status` VARCHAR(32) DEFAULT NULL COMMENT 'pending_receipt, delivered, receipt_failed, received',
  `receipt_at` DATETIME DEFAULT NULL COMMENT 'receipt time',
  `receipt_failure_reason` VARCHAR(255) DEFAULT NULL COMMENT 'receipt failure reason',
  `receipt_payload_json` JSON DEFAULT NULL COMMENT 'raw receipt payload',
  `receipt_operator_admin_user_id` BIGINT DEFAULT NULL COMMENT 'operator admin user id for receipt',
  `receipt_operator_admin_user_name` VARCHAR(64) DEFAULT NULL COMMENT 'operator admin user name for receipt',
  `last_request_id` VARCHAR(128) DEFAULT NULL COMMENT 'latest related business request id',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`delivery_id`),
  KEY `idx_ai_resume_notification_delivery_failure_id_create_time` (`failure_id`, `create_time`),
  KEY `idx_ai_resume_notification_delivery_provider_message_id` (`provider_message_id`),
  KEY `idx_ai_resume_notification_delivery_recipient_admin_create_time` (`recipient_admin_user_id`, `create_time`),
  KEY `idx_ai_resume_notification_delivery_send_status_create_time` (`send_status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ai resume governance notification deliveries';
