-- 00-199 private actor media assets and typed relations.

CREATE TABLE IF NOT EXISTS actor_media_asset (
  asset_id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  media_type VARCHAR(16) NOT NULL COMMENT 'photo,video,pdf',
  category_code VARCHAR(32) DEFAULT NULL,
  storage_provider VARCHAR(32) NOT NULL,
  bucket_code VARCHAR(128) NOT NULL,
  object_key VARCHAR(512) NOT NULL,
  thumbnail_object_key VARCHAR(512) DEFAULT NULL,
  original_name VARCHAR(255) DEFAULT NULL,
  mime_type VARCHAR(128) DEFAULT NULL,
  size_bytes BIGINT DEFAULT NULL,
  duration_ms BIGINT DEFAULT NULL,
  page_count INT DEFAULT NULL,
  process_status VARCHAR(16) NOT NULL DEFAULT 'uploading',
  failure_code VARCHAR(64) DEFAULT NULL,
  failure_message VARCHAR(255) DEFAULT NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'upload',
  version INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  rid VARCHAR(64) DEFAULT NULL,
  create_user_id BIGINT DEFAULT NULL,
  create_user_name VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_user_id BIGINT DEFAULT NULL,
  update_user_name VARCHAR(64) DEFAULT '',
  last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (asset_id),
  UNIQUE KEY uk_actor_media_asset_object (storage_provider, bucket_code, object_key),
  KEY idx_actor_media_asset_user_media_status (user_id, media_type, process_status, deleted, create_time),
  KEY idx_actor_media_asset_owner_category (user_id, category_code, deleted, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='private actor media asset metadata';

CREATE TABLE IF NOT EXISTS actor_media_asset_page (
  page_id BIGINT NOT NULL AUTO_INCREMENT,
  asset_id BIGINT NOT NULL,
  page_no INT NOT NULL,
  image_object_key VARCHAR(1024) NOT NULL,
  process_status VARCHAR(16) NOT NULL DEFAULT 'processing',
  version INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  rid VARCHAR(64) DEFAULT NULL,
  create_user_id BIGINT DEFAULT NULL,
  create_user_name VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_user_id BIGINT DEFAULT NULL,
  update_user_name VARCHAR(64) DEFAULT '',
  last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active_page_no INT GENERATED ALWAYS AS (CASE WHEN deleted = 0 THEN page_no ELSE NULL END) STORED,
  PRIMARY KEY (page_id),
  UNIQUE KEY uk_actor_media_asset_page_active (asset_id, active_page_no),
  KEY idx_actor_media_asset_page_order (asset_id, deleted, page_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='rendered PDF asset pages';

CREATE TABLE IF NOT EXISTS actor_profile_asset (
  relation_id BIGINT NOT NULL AUTO_INCREMENT,
  actor_profile_id BIGINT NOT NULL,
  asset_id BIGINT NOT NULL,
  usage_code VARCHAR(32) NOT NULL COMMENT 'public_photo,public_video,public_resume',
  sort_no INT NOT NULL DEFAULT 0,
  version INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  rid VARCHAR(64) DEFAULT NULL,
  create_user_id BIGINT DEFAULT NULL,
  create_user_name VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_user_id BIGINT DEFAULT NULL,
  update_user_name VARCHAR(64) DEFAULT '',
  last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active_asset_id BIGINT GENERATED ALWAYS AS (CASE WHEN deleted = 0 THEN asset_id ELSE NULL END) STORED,
  PRIMARY KEY (relation_id),
  UNIQUE KEY uk_actor_profile_asset_active (actor_profile_id, usage_code, active_asset_id),
  KEY idx_actor_profile_asset_order (actor_profile_id, usage_code, deleted, sort_no),
  KEY idx_actor_profile_asset_asset (asset_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='profile public asset relations';

CREATE TABLE IF NOT EXISTS actor_work_asset (
  relation_id BIGINT NOT NULL AUTO_INCREMENT,
  experience_id BIGINT NOT NULL,
  asset_id BIGINT NOT NULL,
  usage_code VARCHAR(32) NOT NULL COMMENT 'still,clip',
  sort_no INT NOT NULL DEFAULT 0,
  version INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  rid VARCHAR(64) DEFAULT NULL,
  create_user_id BIGINT DEFAULT NULL,
  create_user_name VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_user_id BIGINT DEFAULT NULL,
  update_user_name VARCHAR(64) DEFAULT '',
  last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active_asset_id BIGINT GENERATED ALWAYS AS (CASE WHEN deleted = 0 THEN asset_id ELSE NULL END) STORED,
  PRIMARY KEY (relation_id),
  UNIQUE KEY uk_actor_work_asset_active (experience_id, usage_code, active_asset_id),
  KEY idx_actor_work_asset_order (experience_id, usage_code, deleted, sort_no),
  KEY idx_actor_work_asset_asset (asset_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='work media relations';

CREATE TABLE IF NOT EXISTS share_card_work (
  relation_id BIGINT NOT NULL AUTO_INCREMENT,
  share_card_id BIGINT NOT NULL,
  experience_id BIGINT NOT NULL,
  sort_no INT NOT NULL DEFAULT 0,
  version INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  rid VARCHAR(64) DEFAULT NULL,
  create_user_id BIGINT DEFAULT NULL,
  create_user_name VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_user_id BIGINT DEFAULT NULL,
  update_user_name VARCHAR(64) DEFAULT '',
  last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active_experience_id BIGINT GENERATED ALWAYS AS (CASE WHEN deleted = 0 THEN experience_id ELSE NULL END) STORED,
  active_sort_no INT GENERATED ALWAYS AS (CASE WHEN deleted = 0 THEN sort_no ELSE NULL END) STORED,
  PRIMARY KEY (relation_id),
  UNIQUE KEY uk_share_card_work_active (share_card_id, active_experience_id),
  UNIQUE KEY uk_share_card_work_sort (share_card_id, active_sort_no),
  KEY idx_share_card_work_order (share_card_id, deleted, sort_no),
  KEY idx_share_card_work_experience (experience_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='share card selected works';

CREATE TABLE IF NOT EXISTS share_card_asset (
  relation_id BIGINT NOT NULL AUTO_INCREMENT,
  share_card_id BIGINT NOT NULL,
  asset_id BIGINT NOT NULL,
  usage_code VARCHAR(32) NOT NULL COMMENT 'cover,gallery,video,resume',
  sort_no INT NOT NULL DEFAULT 0,
  version INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  rid VARCHAR(64) DEFAULT NULL,
  create_user_id BIGINT DEFAULT NULL,
  create_user_name VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_user_id BIGINT DEFAULT NULL,
  update_user_name VARCHAR(64) DEFAULT '',
  last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  active_asset_id BIGINT GENERATED ALWAYS AS (CASE WHEN deleted = 0 THEN asset_id ELSE NULL END) STORED,
  PRIMARY KEY (relation_id),
  UNIQUE KEY uk_share_card_asset_active (share_card_id, usage_code, active_asset_id),
  KEY idx_share_card_asset_order (share_card_id, usage_code, deleted, sort_no),
  KEY idx_share_card_asset_asset (asset_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='share card selected assets';
