CREATE TABLE `actor_ai_profile_card_task` (
  `task_id` VARCHAR(64) NOT NULL COMMENT 'client visible generation task id',
  `user_id` BIGINT NOT NULL COMMENT 'owner user id',
  `actor_profile_id` BIGINT NOT NULL COMMENT 'source actor profile id',
  `share_card_id` BIGINT DEFAULT NULL COMMENT 'created or updated share card id',
  `template_scene_code` VARCHAR(32) NOT NULL COMMENT 'share card style scene code',
  `style_code` VARCHAR(64) NOT NULL COMMENT 'prompt style code',
  `source_image_url` VARCHAR(1024) NOT NULL COMMENT 'primary source portrait/reference image',
  `provider_code` VARCHAR(64) NOT NULL COMMENT 'image model provider code',
  `model_code` VARCHAR(128) DEFAULT NULL COMMENT 'provider model code',
  `generation_mode` VARCHAR(32) NOT NULL DEFAULT 'image_to_image' COMMENT 'image generation mode',
  `prompt_json` LONGTEXT DEFAULT NULL COMMENT 'model independent prompt brief json',
  `prompt_text` LONGTEXT DEFAULT NULL COMMENT 'provider prompt text',
  `negative_prompt` TEXT DEFAULT NULL COMMENT 'negative prompt',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending,running,success,failed',
  `generated_image_url` VARCHAR(1024) DEFAULT NULL COMMENT 'generated image url stored for portfolio preview',
  `failure_reason` VARCHAR(1024) DEFAULT NULL COMMENT 'last failure reason',
  `started_at` DATETIME DEFAULT NULL COMMENT 'generation started at',
  `completed_at` DATETIME DEFAULT NULL COMMENT 'generation completed at',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`task_id`),
  KEY `idx_actor_ai_profile_card_task_user_status` (`user_id`, `status`, `create_time`),
  KEY `idx_actor_ai_profile_card_task_share_card` (`share_card_id`),
  KEY `idx_actor_ai_profile_card_task_profile` (`actor_profile_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI generated actor profile share image tasks';
