-- Platform admin and backend architecture migration baseline
-- Notes:
-- 1. Reuse existing BaseEntity audit columns: version / deleted / rid /
--    create_user_id / create_user_name / create_time /
--    update_user_id / update_user_name / last_update.
-- 2. Keep business truth in MySQL; do not rely on Redis for truth.
-- 3. Avoid physical foreign keys in this phase to reduce deployment coupling.
-- 4. `cooperation_order` keeps its existing cooperation-order semantics in this round and is not altered here.

ALTER TABLE `user`
  ADD COLUMN `invited_by_user_id` BIGINT DEFAULT NULL COMMENT 'referral inviter user id',
  ADD COLUMN `valid_invite_count` INT NOT NULL DEFAULT 0 COMMENT 'cached valid referral count',
  ADD COLUMN `register_device_fingerprint` VARCHAR(128) DEFAULT NULL COMMENT 'device fingerprint at registration',
  ADD INDEX `idx_user_invited_by_user_id` (`invited_by_user_id`),
  ADD INDEX `idx_user_valid_invite_count` (`valid_invite_count`),
  ADD INDEX `idx_user_real_auth_status` (`real_auth_status`);

ALTER TABLE `actor_profile`
  ADD COLUMN `birth_hour` VARCHAR(4) DEFAULT NULL COMMENT 'birth hour key',
  ADD INDEX `idx_actor_profile_birth_hour` (`birth_hour`),
  ADD INDEX `idx_actor_profile_user_id_deleted` (`user_id`, `deleted`);

CREATE TABLE `identity_verification` (
  `verification_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `user_id` BIGINT NOT NULL COMMENT 'user id',
  `real_name` VARCHAR(32) NOT NULL COMMENT 'real name',
  `id_card_no_cipher` VARCHAR(512) NOT NULL COMMENT 'encrypted id card number',
  `id_card_hash` CHAR(64) NOT NULL COMMENT 'sha256 for dedupe',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 pending, 2 approved, 3 rejected',
  `reject_reason` VARCHAR(255) DEFAULT NULL COMMENT 'reject reason',
  `reviewer_id` BIGINT DEFAULT NULL COMMENT 'admin reviewer id',
  `reviewed_at` DATETIME DEFAULT NULL COMMENT 'review time',
  `snapshot_profile_completion` INT DEFAULT NULL COMMENT 'profile completion snapshot on submit',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`verification_id`),
  UNIQUE KEY `uk_identity_verification_id_card_hash` (`id_card_hash`),
  KEY `idx_identity_verification_user_status` (`user_id`, `status`),
  KEY `idx_identity_verification_status_create_time` (`status`, `create_time`),
  KEY `idx_identity_verification_reviewer_id` (`reviewer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='identity verification applications';

CREATE TABLE `invite_code` (
  `invite_code_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `user_id` BIGINT NOT NULL COMMENT 'owner user id',
  `code` VARCHAR(8) NOT NULL COMMENT 'invite code',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 active, 2 disabled',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`invite_code_id`),
  UNIQUE KEY `uk_invite_code_user_id` (`user_id`),
  UNIQUE KEY `uk_invite_code_code` (`code`),
  KEY `idx_invite_code_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='referral invite code';

CREATE TABLE `referral_record` (
  `referral_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `inviter_user_id` BIGINT NOT NULL COMMENT 'inviter user id',
  `invitee_user_id` BIGINT NOT NULL COMMENT 'invitee user id',
  `invite_code_id` BIGINT NOT NULL COMMENT 'invite code id',
  `invite_code_snapshot` VARCHAR(8) NOT NULL COMMENT 'copied invite code',
  `register_device_fingerprint` VARCHAR(128) DEFAULT NULL COMMENT 'invitee device fingerprint',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 pending, 1 valid, 2 invalid, 3 under_review',
  `risk_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '0 normal, 1 risky',
  `risk_reason` VARCHAR(255) DEFAULT NULL COMMENT 'risk reason',
  `registered_at` DATETIME NOT NULL COMMENT 'invitee register time',
  `validated_at` DATETIME DEFAULT NULL COMMENT 'when referral becomes valid',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`referral_id`),
  UNIQUE KEY `uk_referral_record_invitee_user_id` (`invitee_user_id`),
  KEY `idx_referral_record_inviter_status` (`inviter_user_id`, `status`),
  KEY `idx_referral_record_invite_code_snapshot` (`invite_code_snapshot`),
  KEY `idx_referral_record_registered_at` (`registered_at`),
  KEY `idx_referral_record_risk_flag_status` (`risk_flag`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='referral relationship records';

CREATE TABLE `referral_policy` (
  `policy_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `policy_name` VARCHAR(64) NOT NULL COMMENT 'policy name',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '1 enabled, 0 disabled',
  `require_real_auth` TINYINT NOT NULL DEFAULT 1 COMMENT 'inviter requires real auth',
  `require_profile_completion` TINYINT NOT NULL DEFAULT 1 COMMENT 'invitee requires profile completion',
  `profile_completion_threshold` INT NOT NULL DEFAULT 50 COMMENT 'completion threshold percent',
  `same_device_limit` INT NOT NULL DEFAULT 1 COMMENT 'valid accounts per device',
  `hourly_invite_limit` INT NOT NULL DEFAULT 5 COMMENT 'per code hourly limit',
  `auto_grant_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT 'whether auto grant is enabled',
  `grant_rule_json` JSON DEFAULT NULL COMMENT 'grant rule config',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`policy_id`),
  KEY `idx_referral_policy_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='referral policy config';

CREATE TABLE `membership_product` (
  `product_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `product_code` VARCHAR(64) NOT NULL COMMENT 'product code',
  `product_name` VARCHAR(64) NOT NULL COMMENT 'product name',
  `membership_tier` TINYINT NOT NULL COMMENT '0 none, 1 member, 2 vip',
  `duration_days` INT NOT NULL COMMENT 'duration days',
  `list_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'list price',
  `sale_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'sale price',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 active, 2 inactive',
  `benefit_config_json` JSON DEFAULT NULL COMMENT 'benefit config json',
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT 'sort number',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_id`),
  UNIQUE KEY `uk_membership_product_code` (`product_code`),
  KEY `idx_membership_product_status_sort_no` (`status`, `sort_no`),
  KEY `idx_membership_product_membership_tier` (`membership_tier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='membership products';

CREATE TABLE `membership_account` (
  `membership_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `user_id` BIGINT NOT NULL COMMENT 'user id',
  `tier` TINYINT NOT NULL DEFAULT 0 COMMENT '0 none, 1 member, 2 vip',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 inactive, 1 active, 2 expired, 3 closed',
  `effective_time` DATETIME DEFAULT NULL COMMENT 'effective time',
  `expire_time` DATETIME DEFAULT NULL COMMENT 'expire time',
  `source_type` VARCHAR(32) NOT NULL COMMENT 'manual, payment, grant, activity',
  `source_ref_id` BIGINT DEFAULT NULL COMMENT 'source reference id',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`membership_id`),
  UNIQUE KEY `uk_membership_account_user_id` (`user_id`),
  KEY `idx_membership_account_tier_status` (`tier`, `status`),
  KEY `idx_membership_account_expire_time` (`expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='current membership account';

CREATE TABLE `membership_change_log` (
  `change_log_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `user_id` BIGINT NOT NULL COMMENT 'user id',
  `before_tier` TINYINT NOT NULL DEFAULT 0 COMMENT 'before tier',
  `after_tier` TINYINT NOT NULL DEFAULT 0 COMMENT 'after tier',
  `change_reason` VARCHAR(64) NOT NULL COMMENT 'change reason',
  `source_type` VARCHAR(32) NOT NULL COMMENT 'manual, payment, grant, activity',
  `source_ref_id` BIGINT DEFAULT NULL COMMENT 'source reference id',
  `effective_time` DATETIME DEFAULT NULL COMMENT 'effective time',
  `expire_time` DATETIME DEFAULT NULL COMMENT 'expire time',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT 'remark',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`change_log_id`),
  KEY `idx_membership_change_log_user_id_create_time` (`user_id`, `create_time`),
  KEY `idx_membership_change_log_source_type_source_ref_id` (`source_type`, `source_ref_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='membership change logs';

CREATE TABLE `payment_order` (
  `payment_order_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `order_no` VARCHAR(64) NOT NULL COMMENT 'payment order no',
  `user_id` BIGINT NOT NULL COMMENT 'buyer user id',
  `biz_type` VARCHAR(32) NOT NULL COMMENT 'membership_purchase, membership_renewal',
  `biz_ref_id` BIGINT DEFAULT NULL COMMENT 'business ref id',
  `product_id` BIGINT NOT NULL COMMENT 'membership product id',
  `amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'pay amount',
  `currency_code` VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT 'currency code',
  `pay_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 pending, 1 paid, 2 closed, 3 refunded, 4 partial_refunded',
  `pay_channel` VARCHAR(32) DEFAULT NULL COMMENT 'wxpay, alipay',
  `paid_at` DATETIME DEFAULT NULL COMMENT 'paid time',
  `closed_at` DATETIME DEFAULT NULL COMMENT 'closed time',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_order_id`),
  UNIQUE KEY `uk_payment_order_order_no` (`order_no`),
  KEY `idx_payment_order_user_id_pay_status` (`user_id`, `pay_status`),
  KEY `idx_payment_order_product_id` (`product_id`),
  KEY `idx_payment_order_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='payment orders for membership';

CREATE TABLE `payment_transaction` (
  `transaction_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `payment_order_id` BIGINT NOT NULL COMMENT 'payment order id',
  `channel_trade_no` VARCHAR(128) NOT NULL COMMENT 'channel trade no',
  `channel` VARCHAR(32) NOT NULL COMMENT 'wxpay, alipay',
  `trade_type` VARCHAR(32) DEFAULT NULL COMMENT 'jsapi, native, app',
  `amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'transaction amount',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 init, 1 success, 2 failed',
  `callback_payload` JSON DEFAULT NULL COMMENT 'raw callback payload',
  `callback_time` DATETIME DEFAULT NULL COMMENT 'callback time',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`transaction_id`),
  UNIQUE KEY `uk_payment_transaction_channel_trade_no` (`channel_trade_no`),
  KEY `idx_payment_transaction_payment_order_id` (`payment_order_id`),
  KEY `idx_payment_transaction_channel_status` (`channel`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='payment transactions';

CREATE TABLE `refund_order` (
  `refund_order_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `refund_no` VARCHAR(64) NOT NULL COMMENT 'refund no',
  `payment_order_id` BIGINT NOT NULL COMMENT 'payment order id',
  `user_id` BIGINT NOT NULL COMMENT 'user id',
  `refund_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'refund amount',
  `refund_reason` VARCHAR(255) NOT NULL COMMENT 'refund reason',
  `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 pending, 1 approved, 2 rejected',
  `refund_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 init, 1 processing, 2 success, 3 failed',
  `audit_remark` VARCHAR(255) DEFAULT NULL COMMENT 'audit remark',
  `auditor_id` BIGINT DEFAULT NULL COMMENT 'auditor id',
  `audited_at` DATETIME DEFAULT NULL COMMENT 'audit time',
  `channel_refund_no` VARCHAR(128) DEFAULT NULL COMMENT 'channel refund no',
  `refunded_at` DATETIME DEFAULT NULL COMMENT 'refund success time',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`refund_order_id`),
  UNIQUE KEY `uk_refund_order_refund_no` (`refund_no`),
  KEY `idx_refund_order_payment_order_id` (`payment_order_id`),
  KEY `idx_refund_order_user_id` (`user_id`),
  KEY `idx_refund_order_audit_status_refund_status` (`audit_status`, `refund_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='refund orders';

CREATE TABLE `refund_operate_log` (
  `log_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `refund_order_id` BIGINT NOT NULL COMMENT 'refund order id',
  `operator_id` BIGINT NOT NULL COMMENT 'operator id',
  `action_type` VARCHAR(32) NOT NULL COMMENT 'submit, approve, reject, callback, retry',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT 'remark',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `idx_refund_operate_log_refund_order_id_create_time` (`refund_order_id`, `create_time`),
  KEY `idx_refund_operate_log_operator_id` (`operator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='refund operation logs';

CREATE TABLE `card_scene_template` (
  `template_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `template_code` VARCHAR(64) NOT NULL COMMENT 'template code',
  `scene_key` VARCHAR(32) NOT NULL COMMENT 'general, costume, urban, commercial, artistic',
  `template_name` VARCHAR(64) NOT NULL COMMENT 'template name',
  `description` VARCHAR(255) DEFAULT NULL COMMENT 'template description',
  `layout_variant` VARCHAR(32) NOT NULL COMMENT 'compact, spacious, magazine',
  `tier` VARCHAR(16) NOT NULL DEFAULT 'free' COMMENT 'free, paid',
  `required_level` TINYINT NOT NULL DEFAULT 1 COMMENT 'required invite level',
  `membership_required` TINYINT NOT NULL DEFAULT 0 COMMENT '0 no, 1 member required',
  `base_theme_json` JSON NOT NULL COMMENT 'base theme tokens',
  `artifact_preset_json` JSON DEFAULT NULL COMMENT 'share artifact presets',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 active, 2 inactive',
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT 'sort number',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`template_id`),
  UNIQUE KEY `uk_card_scene_template_template_code` (`template_code`),
  KEY `idx_card_scene_template_scene_key_status` (`scene_key`, `status`),
  KEY `idx_card_scene_template_required_level` (`required_level`),
  KEY `idx_card_scene_template_sort_no` (`sort_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='card scene templates';

CREATE TABLE `actor_card_config` (
  `config_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `user_id` BIGINT NOT NULL COMMENT 'user id',
  `actor_profile_id` BIGINT NOT NULL COMMENT 'actor profile id',
  `scene_key` VARCHAR(32) NOT NULL COMMENT 'scene key',
  `template_id` BIGINT NOT NULL COMMENT 'template id',
  `layout_variant` VARCHAR(32) NOT NULL COMMENT 'layout variant',
  `primary_color` VARCHAR(7) DEFAULT NULL COMMENT 'hex primary color',
  `accent_color` VARCHAR(7) DEFAULT NULL COMMENT 'hex accent color',
  `background_color` VARCHAR(7) DEFAULT NULL COMMENT 'hex background color',
  `highlighted_experience_ids` JSON DEFAULT NULL COMMENT 'highlighted experience ids',
  `highlighted_photo_urls` JSON DEFAULT NULL COMMENT 'highlighted photo urls',
  `tag_order_json` JSON DEFAULT NULL COMMENT 'tag order',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`config_id`),
  UNIQUE KEY `uk_actor_card_config_user_scene_key` (`user_id`, `scene_key`),
  KEY `idx_actor_card_config_actor_profile_id` (`actor_profile_id`),
  KEY `idx_actor_card_config_template_id` (`template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='actor card config by scene';

CREATE TABLE `actor_share_preference` (
  `preference_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `user_id` BIGINT NOT NULL COMMENT 'user id',
  `scene_key` VARCHAR(32) NOT NULL COMMENT 'scene key',
  `preferred_artifact` VARCHAR(32) NOT NULL COMMENT 'miniProgramCard, poster, publicCardPage, inviteCard',
  `preferred_tone` VARCHAR(32) DEFAULT NULL COMMENT 'natural, professional, commercial',
  `enable_fortune_theme` TINYINT NOT NULL DEFAULT 0 COMMENT '0 no, 1 yes',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`preference_id`),
  UNIQUE KEY `uk_actor_share_preference_user_scene_key` (`user_id`, `scene_key`),
  KEY `idx_actor_share_preference_preferred_artifact` (`preferred_artifact`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='actor share preferences';

CREATE TABLE `fortune_report` (
  `fortune_report_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `user_id` BIGINT NOT NULL COMMENT 'user id',
  `report_month` DATE NOT NULL COMMENT 'month stored as first day of month',
  `zodiac_animal` VARCHAR(16) NOT NULL COMMENT 'zodiac animal key',
  `zodiac_fortune` JSON DEFAULT NULL COMMENT 'zodiac fortune payload',
  `constellation` VARCHAR(16) NOT NULL COMMENT 'constellation key',
  `constellation_fortune` JSON DEFAULT NULL COMMENT 'constellation fortune payload',
  `ziwei_star` VARCHAR(32) DEFAULT NULL COMMENT 'ziwei star key',
  `ziwei_profile` JSON DEFAULT NULL COMMENT 'ziwei profile payload',
  `lucky_color` VARCHAR(7) NOT NULL COMMENT 'hex lucky color',
  `lucky_color_name` VARCHAR(32) NOT NULL COMMENT 'lucky color name',
  `lucky_color_interpretation` VARCHAR(255) DEFAULT NULL COMMENT 'lucky color interpretation',
  `lucky_number` INT NOT NULL COMMENT 'lucky number',
  `lucky_number_interpretation` VARCHAR(255) DEFAULT NULL COMMENT 'lucky number interpretation',
  `birth_hour` VARCHAR(4) DEFAULT NULL COMMENT 'birth hour used in generation',
  `source_type` VARCHAR(16) NOT NULL DEFAULT 'ai' COMMENT 'ai, fallback',
  `raw_payload` JSON DEFAULT NULL COMMENT 'raw ai payload',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`fortune_report_id`),
  UNIQUE KEY `uk_fortune_report_user_id_report_month` (`user_id`, `report_month`),
  KEY `idx_fortune_report_source_type` (`source_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='monthly fortune reports';

CREATE TABLE `user_entitlement_grant` (
  `grant_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `user_id` BIGINT NOT NULL COMMENT 'user id',
  `grant_type` VARCHAR(32) NOT NULL COMMENT 'invite_eligibility, vip_trial, theme_access',
  `grant_code` VARCHAR(64) NOT NULL COMMENT 'grant code',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 active, 2 expired, 3 revoked',
  `effective_time` DATETIME DEFAULT NULL COMMENT 'effective time',
  `expire_time` DATETIME DEFAULT NULL COMMENT 'expire time',
  `source_type` VARCHAR(32) NOT NULL COMMENT 'manual, activity, payment, policy',
  `source_ref_id` BIGINT DEFAULT NULL COMMENT 'source reference id',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT 'remark',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`grant_id`),
  UNIQUE KEY `uk_user_entitlement_grant_user_id_grant_code` (`user_id`, `grant_code`),
  KEY `idx_user_entitlement_grant_user_id_status` (`user_id`, `status`),
  KEY `idx_user_entitlement_grant_grant_type` (`grant_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='user entitlement grants';

CREATE TABLE `entitlement_rule` (
  `rule_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `rule_code` VARCHAR(64) NOT NULL COMMENT 'rule code',
  `rule_name` VARCHAR(64) NOT NULL COMMENT 'rule name',
  `grant_type` VARCHAR(32) NOT NULL COMMENT 'grant type',
  `trigger_type` VARCHAR(32) NOT NULL COMMENT 'manual, event, scheduled',
  `rule_config_json` JSON DEFAULT NULL COMMENT 'rule config',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '1 enabled, 0 disabled',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`rule_id`),
  UNIQUE KEY `uk_entitlement_rule_rule_code` (`rule_code`),
  KEY `idx_entitlement_rule_grant_type_enabled` (`grant_type`, `enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='entitlement rules';

CREATE TABLE `admin_user` (
  `admin_user_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `account` VARCHAR(64) NOT NULL COMMENT 'login account',
  `password` VARCHAR(255) NOT NULL COMMENT 'hashed password',
  `user_name` VARCHAR(64) NOT NULL COMMENT 'display name',
  `phone` VARCHAR(20) DEFAULT NULL COMMENT 'phone',
  `email` VARCHAR(128) DEFAULT NULL COMMENT 'email',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 active, 2 disabled',
  `last_login_time` DATETIME DEFAULT NULL COMMENT 'last login time',
  `last_login_ip` VARCHAR(64) DEFAULT NULL COMMENT 'last login ip',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`admin_user_id`),
  UNIQUE KEY `uk_admin_user_account` (`account`),
  KEY `idx_admin_user_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='admin users';

CREATE TABLE `admin_role` (
  `admin_role_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `role_code` VARCHAR(64) NOT NULL COMMENT 'role code',
  `role_name` VARCHAR(64) NOT NULL COMMENT 'role name',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 active, 2 inactive',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT 'remark',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`admin_role_id`),
  UNIQUE KEY `uk_admin_role_role_code` (`role_code`),
  KEY `idx_admin_role_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='admin roles';

CREATE TABLE `admin_user_role` (
  `admin_user_role_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `admin_user_id` BIGINT NOT NULL COMMENT 'admin user id',
  `admin_role_id` BIGINT NOT NULL COMMENT 'admin role id',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`admin_user_role_id`),
  UNIQUE KEY `uk_admin_user_role_user_role` (`admin_user_id`, `admin_role_id`),
  KEY `idx_admin_user_role_admin_role_id` (`admin_role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='admin user role mapping';

CREATE TABLE `admin_operation_log` (
  `operation_log_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `admin_user_id` BIGINT NOT NULL COMMENT 'operator admin user id',
  `admin_user_name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'operator admin user name',
  `module_code` VARCHAR(64) NOT NULL COMMENT 'verify, referral, membership, refund, content, system',
  `operation_code` VARCHAR(64) NOT NULL COMMENT 'approve, reject, publish, grant, revoke',
  `target_type` VARCHAR(64) NOT NULL COMMENT 'entity type',
  `target_id` BIGINT DEFAULT NULL COMMENT 'entity id',
  `request_id` VARCHAR(64) DEFAULT NULL COMMENT 'request id',
  `client_ip` VARCHAR(64) DEFAULT NULL COMMENT 'operator client ip',
  `user_agent` VARCHAR(255) DEFAULT NULL COMMENT 'operator user agent',
  `before_snapshot_json` JSON DEFAULT NULL COMMENT 'before snapshot',
  `after_snapshot_json` JSON DEFAULT NULL COMMENT 'after snapshot',
  `operation_result` TINYINT NOT NULL DEFAULT 1 COMMENT '1 success, 2 failed',
  `fail_reason` VARCHAR(255) DEFAULT NULL COMMENT 'failure reason',
  `extra_context_json` JSON DEFAULT NULL COMMENT 'extra business context',
  `confirm_token` VARCHAR(64) DEFAULT NULL COMMENT 'confirm dialog token',
  `confirmed_at` DATETIME DEFAULT NULL COMMENT 'confirm dialog submit time',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`operation_log_id`),
  KEY `idx_admin_operation_log_admin_user_id_create_time` (`admin_user_id`, `create_time`),
  KEY `idx_admin_operation_log_module_code_operation_code` (`module_code`, `operation_code`),
  KEY `idx_admin_operation_log_target_type_target_id` (`target_type`, `target_id`),
  KEY `idx_admin_operation_log_request_id` (`request_id`),
  KEY `idx_admin_operation_log_operation_result_create_time` (`operation_result`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='admin operation logs';

CREATE TABLE `template_publish_log` (
  `publish_log_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `template_id` BIGINT NOT NULL COMMENT 'template id',
  `publish_version` VARCHAR(32) NOT NULL COMMENT 'publish version',
  `action_type` VARCHAR(32) NOT NULL COMMENT 'publish, rollback, disable',
  `published_by` BIGINT NOT NULL COMMENT 'admin user id',
  `publish_note` VARCHAR(255) DEFAULT NULL COMMENT 'publish note',
  `snapshot_json` JSON DEFAULT NULL COMMENT 'template snapshot',
  `published_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'published time',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`publish_log_id`),
  KEY `idx_template_publish_log_template_id_published_at` (`template_id`, `published_at`),
  KEY `idx_template_publish_log_action_type` (`action_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='template publish logs';
