CREATE TABLE `actor_ai_profile_card_page` (
  `page_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'AI profile card album page id',
  `task_id` VARCHAR(64) NOT NULL COMMENT 'parent AI profile card task id',
  `share_card_id` BIGINT DEFAULT NULL COMMENT 'created share card id after task success',
  `page_no` INT NOT NULL COMMENT 'fixed album page order: 1 cover, 2 resume, 3 gallery',
  `page_type` VARCHAR(32) NOT NULL COMMENT 'cover,resume,gallery',
  `prompt_json` LONGTEXT DEFAULT NULL COMMENT 'page-level model independent prompt brief json',
  `prompt_text` LONGTEXT DEFAULT NULL COMMENT 'page-level provider prompt text',
  `negative_prompt` TEXT DEFAULT NULL COMMENT 'page-level negative prompt',
  `provider_code` VARCHAR(64) DEFAULT NULL COMMENT 'image model provider code',
  `model_code` VARCHAR(128) DEFAULT NULL COMMENT 'provider model code',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending,running,success,failed',
  `generated_image_url` VARCHAR(1024) DEFAULT NULL COMMENT 'generated background image url for this page',
  `failure_reason` VARCHAR(1024) DEFAULT NULL COMMENT 'last page failure reason',
  `started_at` DATETIME DEFAULT NULL COMMENT 'page generation started at',
  `completed_at` DATETIME DEFAULT NULL COMMENT 'page generation completed at',
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `rid` VARCHAR(64) DEFAULT NULL,
  `create_user_id` BIGINT DEFAULT NULL,
  `create_user_name` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user_id` BIGINT DEFAULT NULL,
  `update_user_name` VARCHAR(64) DEFAULT '',
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`page_id`),
  UNIQUE KEY `uk_actor_ai_profile_card_page_task_no` (`task_id`, `page_no`),
  UNIQUE KEY `uk_actor_ai_profile_card_page_task_type` (`task_id`, `page_type`),
  KEY `idx_actor_ai_profile_card_page_task_status` (`task_id`, `status`, `page_no`),
  KEY `idx_actor_ai_profile_card_page_share_card` (`share_card_id`, `page_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI generated actor profile share album pages';
