-- 00-199 governed DeepSeek profile import configuration and sanitized audits.
CREATE TABLE IF NOT EXISTS ai_profile_import_config (
  config_id BIGINT NOT NULL AUTO_INCREMENT, provider_code VARCHAR(32) NOT NULL DEFAULT 'deepseek', display_name VARCHAR(128) NOT NULL, enabled TINYINT NOT NULL DEFAULT 0, endpoint VARCHAR(512) NOT NULL, model_name VARCHAR(128) NOT NULL, connect_timeout_ms INT NOT NULL, read_timeout_ms INT NOT NULL, max_input_chars INT NOT NULL, max_output_tokens INT NOT NULL, per_user_daily_limit INT NOT NULL, secret_config_ciphertext TEXT DEFAULT NULL, secret_mask_json VARCHAR(512) DEFAULT NULL, last_test_status VARCHAR(32) DEFAULT NULL, last_test_message VARCHAR(255) DEFAULT NULL, last_test_at DATETIME DEFAULT NULL, version INT NOT NULL DEFAULT 0, deleted TINYINT NOT NULL DEFAULT 0, rid VARCHAR(64) DEFAULT NULL, create_user_id BIGINT DEFAULT NULL, create_user_name VARCHAR(64) DEFAULT '', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_user_id BIGINT DEFAULT NULL, update_user_name VARCHAR(64) DEFAULT '', last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (config_id), UNIQUE KEY uk_ai_profile_import_config_provider (provider_code, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='governed profile import provider config';
CREATE TABLE IF NOT EXISTS ai_profile_import_config_audit (
  audit_id BIGINT NOT NULL AUTO_INCREMENT, config_id BIGINT NOT NULL, action_code VARCHAR(64) NOT NULL, before_public_config_json TEXT DEFAULT NULL, after_public_config_json TEXT DEFAULT NULL, before_secret_mask_json VARCHAR(512) DEFAULT NULL, after_secret_mask_json VARCHAR(512) DEFAULT NULL, operator_id BIGINT DEFAULT NULL, operator_name VARCHAR(128) DEFAULT NULL, result_status VARCHAR(32) NOT NULL, message VARCHAR(255) DEFAULT NULL, version INT NOT NULL DEFAULT 0, deleted TINYINT NOT NULL DEFAULT 0, rid VARCHAR(64) DEFAULT NULL, create_user_id BIGINT DEFAULT NULL, create_user_name VARCHAR(64) DEFAULT '', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_user_id BIGINT DEFAULT NULL, update_user_name VARCHAR(64) DEFAULT '', last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (audit_id), KEY idx_ai_profile_import_config_audit_config (config_id, deleted, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='sanitized profile import configuration audit';
CREATE TABLE IF NOT EXISTS ai_profile_import_request_audit (
  audit_id BIGINT NOT NULL AUTO_INCREMENT, request_id VARCHAR(64) NOT NULL, user_id BIGINT NOT NULL, config_id BIGINT NOT NULL, model_name VARCHAR(128) NOT NULL, status VARCHAR(32) NOT NULL, input_length INT NOT NULL, candidate_count INT NOT NULL DEFAULT 0, work_count INT NOT NULL DEFAULT 0, conflict_count INT NOT NULL DEFAULT 0, elapsed_ms BIGINT DEFAULT NULL, error_code VARCHAR(64) DEFAULT NULL, profile_version BIGINT NOT NULL DEFAULT 0, work_library_version BIGINT NOT NULL DEFAULT 0, apply_payload_sha256 CHAR(64) DEFAULT NULL, apply_status VARCHAR(32) DEFAULT NULL, apply_result_summary_json TEXT DEFAULT NULL, applied_at DATETIME DEFAULT NULL, version INT NOT NULL DEFAULT 0, deleted TINYINT NOT NULL DEFAULT 0, rid VARCHAR(64) DEFAULT NULL, create_user_id BIGINT DEFAULT NULL, create_user_name VARCHAR(64) DEFAULT '', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_user_id BIGINT DEFAULT NULL, update_user_name VARCHAR(64) DEFAULT '', last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (audit_id), UNIQUE KEY uk_ai_profile_import_request_user_request (user_id, request_id), KEY idx_ai_profile_import_request_status (status, deleted, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='sanitized profile import request and apply audit';
