package com.kaipai.service.ai.impl;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*; import com.kaipai.common.exception.BizException; import com.kaipai.mapper.ai.AiProfileImportRequestAuditMapper; import com.kaipai.model.ai.dto.*; import com.kaipai.service.ai.*; import com.kaipai.service.ai.profileimport.*; import com.kaipai.integration.ai.profileimport.DeepSeekProfileTextExtractor; import com.fasterxml.jackson.databind.*; import org.junit.jupiter.api.*;
class ProfileImportServiceImplTest { private ProfileImportConfigService config; private DeepSeekProfileTextExtractor extractor; private AiProfileImportRequestAuditMapper audit; private ProfileImportRateLimiter limiter; private ProfileImportServiceImpl service; @BeforeEach void setup(){config=mock(ProfileImportConfigService.class);extractor=mock(DeepSeekProfileTextExtractor.class);audit=mock(AiProfileImportRequestAuditMapper.class);limiter=mock(ProfileImportRateLimiter.class);when(config.runtimeConfig()).thenReturn(new ProfileImportRuntimeConfig(3L,"https://api.deepseek.com/chat/completions","deepseek-chat","sk-memory",20000,10));service=new ProfileImportServiceImpl(config,extractor,audit,limiter,new ObjectMapper());}
 @Test void disabledCapabilityRejectsBeforeModelCall(){when(config.capability()).thenReturn(new ProfileImportCapabilityRespDTO(false,"disabled"));var e=assertThrows(BizException.class,()->service.extract(7L,request("文本")));assertEquals(46001,e.getCode());verifyNoInteractions(extractor);}
 @Test void emptyAndTooLongInputsHaveStableErrors(){when(config.capability()).thenReturn(new ProfileImportCapabilityRespDTO(true,null));assertEquals(46003,assertThrows(BizException.class,()->service.extract(7L,request(" "))).getCode());var longText="x".repeat(20001);assertEquals(46004,assertThrows(BizException.class,()->service.extract(7L,request(longText))).getCode());}
 @Test void dailyLimitRejectsBeforeModelCall(){when(config.capability()).thenReturn(new ProfileImportCapabilityRespDTO(true,null));when(limiter.allow(7L,10)).thenReturn(false);var e=assertThrows(BizException.class,()->service.extract(7L,request("文本")));assertEquals(46005,e.getCode());verifyNoInteractions(extractor);}
 @Test void successUsesRuntimeConfigAndWritesOnlySanitizedAudit()throws Exception{when(config.capability()).thenReturn(new ProfileImportCapabilityRespDTO(true,null));when(limiter.allow(7L,10)).thenReturn(true);var runtime=new ProfileImportRuntimeConfig(3L,"https://api.deepseek.com/chat/completions","deepseek-chat","sk-memory",20000,10);when(config.runtimeConfig()).thenReturn(runtime);when(extractor.extract(any(),eq("sk-memory"),any(),eq("req-1"))).thenReturn(new ObjectMapper().readTree("{\"profileCandidates\":[{}],\"workCandidates\":[{},{}]}"));service.extract(7L,request("演员王火火"));var captor=org.mockito.ArgumentCaptor.forClass(com.kaipai.model.ai.entity.AiProfileImportRequestAudit.class);verify(audit).insert(captor.capture());assertEquals(5,captor.getValue().getInputLength());assertEquals(1,captor.getValue().getCandidateCount());assertEquals(2,captor.getValue().getWorkCount());}
 private ProfileImportExtractReqDTO request(String text){var d=new ProfileImportExtractReqDTO();d.setRequestId("req-1");d.setRawText(text);d.setScene("full_profile");return d;}}


